services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_MULTIPLE_DATABASES: weather, weather_test
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u postgres"]
      interval: 2s
      timeout: 5s
      retries: 5