services:
  proxy:
    image: nginx
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/cert/:/etc/nginx/cert/
    ports:
     - 443:443
    
  postgres:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u postgres"]
      interval: 20s
      timeout: 5s
      retries: 5
    ports:
      - 5442:5432
  
  postgres-test:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5443:5432